---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: myappp
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./
  prune: true
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: myteam
